backend:
  name: git-gateway
  branch: staging
  #publish_mode: editorial_workflow
media_folder: "static/img" # Folder where user uploaded files should go
media_library: "img"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
