# This is a basic workflow to help you get started with Actions

name: build and deploy website
env:
  OUTPUT_PATH: ${{ github.workspaces }}/.output
  HUGO_VERSION : 0.65.3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Hugo
      id : get-hugo
      uses: peaceiris/actions-hugo@v2.4.6
        with:
           hugo-version: ${HUGO_VERSION}
